//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDb1
{
    using System;
    using System.Collections.Generic;
    
    public partial class actividadproyectos
    {
        public int IDActividadProyectos { get; set; }
        public string Estado { get; set; }
        public string Tiempo { get; set; }
        public string FechaActividad { get; set; }
        public int IDProyecto { get; set; }
        public int IDHistoriasUsuario { get; set; }
        public int IDUsername { get; set; }
    }
}
