//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDb1
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public int IDUsername { get; set; }
        public System.DateTime FechaContratacion { get; set; }
        public int IDPuestoTrabajo { get; set; }
    }
}
