//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDb1
{
    using System;
    using System.Collections.Generic;
    
    public partial class historiasusuario
    {
        public int IDHistoriasUsuario { get; set; }
        public string Caracteristidas { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int IDUsuario { get; set; }
        public int IDProyecto { get; set; }
    }
}
