//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDb1
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_e_d
    {
        public int IDProyecto { get; set; }
        public string PseudoNombre { get; set; }
        public string NombreProyecto { get; set; }
        public string URL_Table_Treloo { get; set; }
        public string URL_GitHub { get; set; }
        public string EtiquetaEstado { get; set; }
        public string FechaAsignacion { get; set; }
        public string FechaEntrega { get; set; }
        public int IDSolicitudProyecto { get; set; }
        public int IDEquipoTrabajo { get; set; }
    }
}
