//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDb1
{
    using System;
    using System.Collections.Generic;
    
    public partial class privilegios
    {
        public int IDPrivilegio { get; set; }
        public string NombrePrivilegio { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
