//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDb1
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitudesproyecto
    {
        public int IDSolicitudProyecto { get; set; }
        public string NombreP { get; set; }
        public string TecnologiasAplicables { get; set; }
        public decimal Presupuesto { get; set; }
        public int IDUsuario { get; set; }
    }
}
