//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDb1
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int IDUsuario { get; set; }
        public string Contraseña { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string NombreCompleto { get; set; }
        public string Direccion_Calle { get; set; }
        public string Direccion_Ciudad { get; set; }
        public string Direccion_Departamento { get; set; }
        public string CorreoElectronico { get; set; }
        public string FechaNacimineto { get; set; }
        public int IDRol { get; set; }
    }
}
